from . import pregunta_01
from . import pregunta_02
from . import pregunta_03
from . import pregunta_04
from . import pregunta_05
from . import pregunta_06
from . import pregunta_07
from . import pregunta_08
from . import pregunta_09
from . import pregunta_10
from . import pregunta_11
from . import pregunta_12